server {
    listen 80;

    root /usr/share/nginx/html;

    # learning-path app
    location /learning-path/ {
        try_files $uri $uri/ /learning-path/index.html;
    }

    # ai-games app
    location /ai-games/ {
        try_files $uri $uri/ /ai-games/index.html;
    }

    # redirect root to learning-path
    location / {
        return 302 /learning-path/;
    }
}
