-- Databricks Delta Lake Schema for CCH AI Academy
-- Catalog: dc_adb-landing-zone-002
-- Schema: cch_ai_academy
--
-- All IDs are UUIDs (STRING) generated by the application
-- Default values handled in Python/SQLAlchemy

-- 1. Users table
CREATE TABLE IF NOT EXISTS users (
    username STRING NOT NULL,
    created_at TIMESTAMP
);

-- 2. Learning Paths table
CREATE TABLE IF NOT EXISTS learning_paths (
    id STRING NOT NULL,
    name STRING,
    created_at TIMESTAMP,
    username STRING,
    job_function STRING,
    experience STRING,
    time_available STRING,
    interests STRING,
    recommended_path STRING,
    ai_summary STRING,
    total_submodules INT,
    status STRING
);

-- 3. Responses table
CREATE TABLE IF NOT EXISTS responses (
    id STRING NOT NULL,
    learning_path_id STRING,
    question_id STRING,
    selected_option STRING,
    written_answer STRING
);

-- 4. Learning Progress table
CREATE TABLE IF NOT EXISTS learning_progress (
    id STRING NOT NULL,
    username STRING NOT NULL,
    learning_path_id STRING NOT NULL,
    progress_json STRING NOT NULL,
    overall_progress INT,
    updated_at TIMESTAMP
);

-- 5. User Sessions table
CREATE TABLE IF NOT EXISTS user_sessions (
    id STRING NOT NULL,
    username STRING NOT NULL,
    login_time TIMESTAMP,
    logout_time TIMESTAMP
);

-- 6. Screen Activity table
CREATE TABLE IF NOT EXISTS screen_activity (
    id STRING NOT NULL,
    username STRING NOT NULL,
    session_id STRING NOT NULL,
    screen_name STRING NOT NULL,
    enter_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP NOT NULL,
    duration_seconds INT NOT NULL
);

-- 7. User Ratings table
CREATE TABLE IF NOT EXISTS user_ratings (
    id STRING NOT NULL,
    username STRING NOT NULL,
    learning_path_id STRING NOT NULL,
    rating DOUBLE NOT NULL,
    comment STRING,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 8. Scenarios table
CREATE TABLE IF NOT EXISTS scenarios (
    id STRING NOT NULL,
    title STRING NOT NULL,
    function STRING NOT NULL,
    description STRING NOT NULL,
    problem STRING NOT NULL,
    icon STRING NOT NULL,
    difficulty STRING NOT NULL,
    estimated_time STRING NOT NULL,
    old_way_time STRING,
    old_way_steps STRING,
    steps STRING NOT NULL,
    benefits STRING NOT NULL,
    learning_modules STRING NOT NULL,
    flagship INT,
    active INT,
    hidden INT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 9. Scenario Ratings table
CREATE TABLE IF NOT EXISTS scenario_ratings (
    id STRING NOT NULL,
    scenario_id STRING NOT NULL,
    username STRING NOT NULL,
    rating INT NOT NULL,
    comment STRING,
    created_at TIMESTAMP
);

-- 10. Scenario Suggestions table
CREATE TABLE IF NOT EXISTS scenario_suggestions (
    id STRING NOT NULL,
    username STRING NOT NULL,
    suggestion STRING NOT NULL,
    status STRING,
    admin_notes STRING,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
